spring.application.name=demo2_project
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb
spring.datasource.username=root
spring.datasource.password=HelloWorld@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
